version: '3.7'
services:
  web:
    build:
      context: ./website
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --workers=4 --access-logfile - --error-logfile - --log-file - --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    env_file:
      - ./.env.prod.db
  nginx:
    image: 'docker.io/bitnami/nginx:latest'
    #build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/blog.conf:ro
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:8080
    depends_on:
      - web
  pgbouncer:
    image: 'docker.io/edoburu/pgbouncer'
    depends_on:
      - db
    env_file:
      - ./.env.prod
  memcached:
    image: memcached:alpine
volumes:
  postgres_data:
  static_volume:
  media_volume:
