version: '3.7'
services:
  web:
    build: ./website
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./website/:/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=hello_django
      - POSTGRESQL_PASSWORD=hello_django
      - POSTGRESQL_DATABASE=hello_django_dev
volumes:
  postgres_data:
