version: '3.7'
services:
  haraka:
    build: .
    ports:
      - 25:8025
    environment:
      - MAIL_USER=user1
      - MAIL_PASSWORD=pass1
      - TLS_KEY_C=RU
      - TLS_KEY_ST=Moscow
      - TLS_KEY_L=Moscow
      - TLS_KEY_O=
      - TLS_KEY_OU=
      - TLS_KEY_CN=example.com