# Generated by Django 3.1.5 on 2021-01-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210105_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='rootpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
    ]
