# Generated by Django 3.1.5 on 2021-01-06 21:23

import blog.streamblocks
from django.db import migrations, models
import django.utils.timezone
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210106_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', label='Text')), ('section_heading', blog.streamblocks.SectionHeading()), ('blockquote', blog.streamblocks.Blockquote()), ('single_img', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock('Image')), ('url', wagtail.core.blocks.URLBlock(label='URL', required=False)), ('caption', wagtail.core.blocks.CharBlock(label='Caption', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
    ]
