# Generated by Django 3.1.5 on 2021-01-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('blog', '0007_flatpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(blank=True, help_text='Your Twitter page URL', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Your Facebook page URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='Your GitHub page URL', null=True)),
                ('copyright', models.CharField(blank=True, max_length=400, null=True, verbose_name='Copyright')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer Settings',
            },
        ),
    ]
