# Generated by Django 3.1.5 on 2021-01-07 09:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('blog', '0008_footersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', wagtail.core.fields.StreamField([('page', wagtail.documents.blocks.DocumentChooserBlock(label='Page'))])),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Main Menu',
            },
        ),
    ]
