# Generated by Django 3.1.5 on 2021-01-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210107_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='home_link_text',
            field=models.CharField(default='My site', max_length=255, verbose_name='Home Link Text'),
            preserve_default=False,
        ),
    ]
