# Generated by Django 3.1.5 on 2021-01-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_mainmenu_home_link_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='unsafe_counters',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='HTML for counters'),
        ),
    ]
