# Generated by Django 3.1.5 on 2021-01-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_footersettings_unsafe_counters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='parent_page',
            new_name='menu_entity',
        ),
    ]
